apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: sib22-idaustria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/dalexkraus/sib22idaustria-backend/backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sib22-idaustria
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: sib22-idaustria
spec:
  ingressClassName: traefik-public
  rules:
  - host: sib22idaustria.cc
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080
