apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: sib22-idaustria
  labels:
    app: backend
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: "<id_austria_client_secret>"
  OIDC_CLIENT_ID: "<id_austria_client_id>"
  OIDC_REDIRECT_URI: "https://sib22idaustria.cc/api/v1/callback"
  FRONTEND_BASE_URL: "http://sib22idaustria.cc"
  OIDC_AUTHORITY: "https://eid2.oesterreich.gv.at"
  JWT_AUDIENCE: "<same_as_oidc_client_id>"
  JWT_ISSUER: "https://eid2.oesterreich.gv.at"
  API_HOST: "http://sib22idaustria.cc"